spring.application.name=controle-financeiro
server.port=8081
spring.datasource.url=${BANCO_DE_DADOS_URL}
spring.datasource.username=${USUARIO_BANCO_DE_DADOS}
spring.datasource.password=${SENHA_BANCO_DE_DADOS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=ERROR