spring.application.name=controle-financeiro
server.port=8081
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/controle_financeiro
spring.datasource.username=root
spring.datasource.password=*Gui1709*06
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=ERROR
api.error.bad-request=/errors/bad-request
api.error.not-found=/errors/not-found
api.error.conflict=/erros/conflict
api.base-url=http://localhost:8081